language: php

php:
  - 7
  - 5.6
  - 5.5
  - hhvm

before_script:
  - pip install --user codecov
  - composer self-update && composer install --dev

script:
  - ./vendor/bin/phpunit  --coverage-clover=coverage.xml

after_success:
  - codecov
